const Animation = () => {
  return (
    <div className="animation">
    <Head>
        <title>Mahmoud Ahmed</title>
        <meta name="description" content="Portfolio Website Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="outer">
        <div className="inner"></div>
        <img className="anim" src="/Mahmoud LOgo hero.png" alt="logo" />
      </div>
    </div>
  );
};

export default Animation;
