import Head from "next/head";
import HomePage from "../comps/Home";
import About from "../comps/About";
import Projects from "../comps/Projects";
import Contacts from "../comps/Contacts";

export default function Home() {
  return (
    <section>
      <Head>
        <title>Mahmoud Ahmed</title>
        <meta name="description" content="Portfolio Website Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage />
      <About />
      <Projects />
      <Contacts />
    </section>
  );
}
